# Generated by Django 5.1.4 on 2026-01-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='If True, admin must change password on next login.'),
        ),
    ]
