# Generated by Django 5.2 on 2026-01-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
