# Generated by Django 5.1.4 on 2026-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0002_education_experience_skill_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
