# Generated by Django 5.1.4 on 2026-01-12 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0004_alter_userprofile_user_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'User Registration'), ('JOB_CREATE', 'Job Created'), ('JOB_UPDATE', 'Job Updated'), ('APPLIED', 'Job Applied'), ('STATUS_CHANGE', 'Application Status Changed'), ('PROFILE_UPDATE', 'Profile Updated')], max_length=50)),
                ('description', models.TextField()),
                ('target_object', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
