# Generated by Django 5.2 on 2026-01-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0005_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_stage',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('HR_ROUND', 'HR Round'), ('TECH_ROUND', 'Technical Round'), ('FINAL_ROUND', 'Final Round'), ('HIRED', 'Hired')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
