# Generated by Django 5.2 on 2026-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0006_jobapplication_interview_stage_jobapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='task_submission',
            field=models.FileField(blank=True, null=True, upload_to='candidate_tasks/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='task_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
