# Generated by Django 5.2 on 2026-01-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0007_jobapplication_task_submission_and_more'),
        ('organization', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organization.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application_tracking.jobadvert'),
        ),
    ]
