# Generated by Django 5.2 on 2026-02-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0008_jobapplication_job_alter_jobapplication_job_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('final_score', models.IntegerField(default=0, help_text='AI Score 0-100')),
                ('ai_decision', models.CharField(choices=[('PENDING', 'Pending Decision'), ('HIRE', 'Recommended for Hire'), ('REJECT', 'Rejected by AI'), ('MANUAL_REVIEW', 'Needs Manual Review')], default='PENDING', max_length=20)),
                ('ai_feedback', models.TextField(blank=True, help_text='Evaluator feedback', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='application_tracking.jobapplication')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AIInterviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AI', 'AI Interviewer'), ('USER', 'Candidate'), ('SYSTEM', 'System Event')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='application_tracking.aiinterviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
