# Generated by Django 5.2 on 2026-02-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0009_aiinterviewsession_aiinterviewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('HR', 'HR Round (Form)'), ('TECH', 'Technical Round (Code/Task)')], max_length=10)),
                ('task_content', models.TextField(help_text='The question or instruction for the candidate')),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='task_responses/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='PENDING', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='application_tracking.jobapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
