# Generated by Django 5.2 on 2026-02-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0010_candidatetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.IntegerField(default=0, help_text='Overall AI Score'),
        ),
    ]
